import React from 'react';
import { createRoot } from 'react-dom/client';
import '@ionic/react/css/core.css';
import '@ionic/react/css/normalize.css';
import '@ionic/react/css/structure.css';
import '@ionic/react/css/typography.css';
import '@ionic/react/css/palettes/dark.always.css';
import './theme/variables.css';
import './theme/global.css';
import App from './app/App';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
